'use strict';

const detector = require('./detector');
const scaffolder = require('./scaffolder');
const stealth = require('./stealth');
const configLoader = require('./config');
const llm = require('./llm');
const { loadEnv } = require('./env');

const VALID_MODES = ['new', 'existing', 'auto'];

/**
 * Đọc --mode=<value>; mặc định 'new'.
 * @throws nếu giá trị không hợp lệ
 */
function parseMode(value) {
  const mode = value === undefined ? 'new' : value;
  if (!VALID_MODES.includes(mode)) {
    throw new Error(`Invalid --mode="${mode}". Valid values: ${VALID_MODES.join(', ')}`);
  }
  return mode;
}

/**
 * Luồng scaffold mặc định: config → detect → scaffold → stealth.
 */
async function runInit({ targetDir, mode }) {
  console.log('');

  let autoGeneratedDocs = null;
  if (mode === 'auto') {
    loadEnv(targetDir);
    console.log('[speckit-ai] 🤖 Mode: auto (AI Auto-generation)');
    console.log('[speckit-ai] 🔍 Scanning source code and requesting AI completion...');
    try {
      autoGeneratedDocs = await llm.generateDocs(targetDir);
      console.log('[speckit-ai] ✅ Successfully received AI completion!');
    } catch (err) {
      console.error('[speckit-ai] Aborting. Set an API key in your environment or .env, or run with --mode=new.');
      throw err;
    }
  } else {
    console.log(`[speckit-ai] ⚙️  Mode: ${mode === 'existing' ? 'existing (AI-PROMPT skeletons)' : 'new (Best Practices templates)'}`);
  }

  console.log('');

  // Step 1: Config
  const userConfig = configLoader.loadConfig(targetDir);
  const customTemplatesDir = userConfig.templatesDir || null;
  if (customTemplatesDir) {
    console.log(`[speckit-ai] ⚙️  Custom templates dir: ${customTemplatesDir}`);
  }

  // Step 2: Detect framework / structure
  const projectConfig = detector.detect(targetDir);
  if (projectConfig.type === 'single') {
    console.log(`[speckit-ai] 🔍 Detected: ${projectConfig.framework} / ${projectConfig.packageManager}`);
  } else {
    console.log(`[speckit-ai] 🔍 Detected Monorepo (${projectConfig.tool}) with ${projectConfig.subProjects.length} sub-projects`);
  }
  console.log('');

  // Step 3: Scaffold
  console.log('[speckit-ai] 📝 Creating documentation structure...');
  const { created, skipped } = scaffolder.scaffold({ targetDir, projectConfig, mode, customTemplatesDir, autoGeneratedDocs });
  console.log('');
  console.log(`[speckit-ai] ✅ ${created} file(s) created, ${skipped} file(s) skipped (already exist)`);
  console.log('');

  // Step 4: Stealth mode
  stealth.apply(targetDir);
  console.log('');

  // Done
  console.log('[speckit-ai] 🎉 Done!');
  if (mode === 'existing') {
    console.log('[speckit-ai] 👉 Next: ask your AI agent to read docs/ and fill in the AI-PROMPT sections based on the actual codebase.');
  } else {
    console.log('[speckit-ai] 👉 Next: open .agents/AGENTS.md and adjust it for your project.');
  }
  console.log('');
}

module.exports = { runInit, parseMode, VALID_MODES };
